src/models.py
from src import db


class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(length=30), nullable=False)
    email = db.Column(db.String(length=64), nullable=False)
    sent_date = db.Column(db.DateTime, nullable=False)
    message = db.Column(db.Text(length=150), nullable=False)
    

    def __repr__(self):
        return f"ID:{self.id}, name: {self.name}, {self.email}, message: {self.message}, sent_date: {self.sent_date}"


class AdminUser(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(length=30), nullable=False)
    email = db.Column(db.String(length=64), nullable=False, unique=True)
    password = db.Column(db.String(length=60), nullable=False)
    last_login = db.Column(db.DateTime, nullable = False)


    def __repr__(self):
        return f"ID: {self.id}, name: {self.name}, email: {self.email}, password: {self.password}"

src/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, TextAreaField, PasswordField
from wtforms.validators import DataRequired, Length, Email, InputRequired, EqualTo


class ContactForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), InputRequired()])
    email = StringField("Email", validators=[DataRequired() ,Email(), InputRequired(message="Please provide email")])
    message = TextAreaField("Message (max 900 char)" ,validators=[ DataRequired(), Length(1, 900), InputRequired()])
    submit = SubmitField("Send")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email(), InputRequired()])
    password = PasswordField("Password", validators=[DataRequired(), InputRequired()])
    rememberPassword = BooleanField("Remember Password", default=False)
    submit = SubmitField("Login")


class SignupForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), InputRequired()])
    email = StringField("Email", validators=[DataRequired(), Email(), InputRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(6,24), InputRequired()])
    cnf_password = PasswordField("Confirm password", validators=[DataRequired(), Length(6,24), InputRequired(), EqualTo('password', "password didn't match")])
    submit = SubmitField("Signup")


class AccountUpdateForm(FlaskForm):
    name = StringField("Update Name", validators=[DataRequired(), InputRequired()])
    email = StringField("Update Email", validators=[DataRequired(), Email(), InputRequired()])
    password = PasswordField("Update Password", validators=[DataRequired(), Length(6,24), InputRequired()])
    cnf_password = PasswordField("Confirm password", validators=[DataRequired(), Length(6,24), InputRequired(), EqualTo('password', "password didn't match")])
    submit = SubmitField("Update Details")

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


def create_app(test_config=True):
    app = Flask(__name__)

    app.config['ENV'] = 'development'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test_blog.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    app.config['SECRET_KEY'] = 'BCTsMiRWe5XVg44kosryuQ'

    return app

app = create_app()
db = SQLAlchemy(app)

from src import routes
from src.auth import auth, admin
from src.errors import errors

# blueprints
app.register_blueprint(auth)
app.register_blueprint(admin)
app.register_blueprint(errors)

src/auth.py
from datetime import datetime, timezone
from functools import wraps
from flask import Blueprint, request, render_template, redirect, url_for, flash, session, g
from src.forms import LoginForm, SignupForm, AccountUpdateForm
from werkzeug.security import check_password_hash, generate_password_hash

from src.models import Message, AdminUser
from src import db
from src.utils import utc2local


auth = Blueprint('auth', __name__, url_prefix='/auth')
admin = Blueprint('admin', __name__, url_prefix='/admin')


# view decorators
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get('user_id') is None:
            return redirect(url_for('auth.user_login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function

# routes
@auth.route('/login', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = AdminUser.query.filter_by(email=form.email.data).first()
            if check_password_hash(user.password, form.password.data):
                session['user_id'] = user.id
                flash("Logged in successfully!", "success")
                return redirect(url_for("admin.dashboard_page"))
            else:
                flash("Sorry! couldn't login.", "danger")
                return redirect(".user_login")
        except:
            user = None
            flash("Oops! something went wrong.", 'warning')
            return redirect(".user_login")

    return render_template("login.html", form=form)


@auth.route("/logout", methods=['GET'])
def user_logout():
    session.pop('user_id', None)
    flash("Logged out successfully!", 'info')
    return redirect(url_for(".user_login"))


@auth.route("/register", methods=['GET', 'POSt'])
def user_register():
    form = SignupForm()
    if form.validate_on_submit():
        hashPassword = generate_password_hash(form.password.data)
        user = AdminUser(name=form.name.data, email=form.email.data,
                         password=hashPassword, last_login=datetime.now(tz=timezone.utc))
        try:
            db.session.add(user)
            db.session.commit()
            flash("Account created successfully!", 'success')
            return redirect(url_for("admin.dashboard_page"))
        except:
            flash("Sorry! couldn't create account!", 'danger')
            return redirect(url_for(".user_register"))

    return render_template("signup.html", form=form)


@admin.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard_page():
    if request.method == 'GET':
        try:
            user = AdminUser.query.get(session['user_id'])
            messgs = Message.query.all()
            for messg in messgs:
                messg.sent_date = utc2local(
                    messg.sent_date).strftime("%b %d, %Y - %I:%M %p")
        except:
            messgs = None

        return render_template("admin-dashboard.html", messages=messgs, user = user)
    else:
        if request.args.get('delete'):
            id = int(request.args.get('id'))
            messg = Message.query.filter_by(id=id).first()
            db.session.delete(messg)
            db.session.commit()
            return redirect(url_for('.dashboard_page'))


@admin.route("/settings", methods=['GET', 'POST'])
def account_settings():
    user = AdminUser.query.get(session['user_id'])
    form = AccountUpdateForm()
    if form.validate_on_submit():
        pass
    return render_template("admin-settings.html",form = form, user = user)

src/routes.py
from src import app
from src.models import Message
from flask import render_template, send_from_directory, request, redirect, flash, url_for
from src import db
from datetime import datetime, timezone
from src.forms import ContactForm

@app.route('/robots.txt')
def static_from_root():
    return send_from_directory(app.static_folder, request.path[1:])



@app.route("/home")
@app.route("/index")
@app.route("/")
def home_page():
    return render_template("index.html")

@app.route("/contact", methods=['GET', 'POST'])
def contact_page():
    form = ContactForm()

    if form.validate_on_submit():
        messg = Message(name=form.name.data, email=form.email.data, sent_date=datetime.now(tz=timezone.utc), message=form.message.data)
        try:
            db.session.add(messg)
            db.session.commit()
            flash('Message Sent successfully!', 'success')
            return redirect(url_for('contact_page'))
        except:
            flash('Sorry! there was an error.','danger')
            return redirect(url_for("contact_page"))
    
    return render_template("contact.html", form = form )


@app.route("/admin/login", methods=['GET', 'POST'])
def admin_login():
    return "Admin logged in successfull!"

src/templates/_footer.html
{% block footer %}

    <div class="container pt-3">
      <div class="row">
      <div class="col-md-6 mx-auto mb-3">
        <div class="d-inline-flex flex-row align-item-center">
          <img src="{{url_for("static", filename="mandala32px.png")}}" width="28px" height="28px" alt="footer-logo">
          <span class="ps-2"><h4>Bhaskar Nar</h4></span>
        </div>
        
        <ul class="list-unstyled">
          <li><p class="text-secondary">
            <i class="bi bi-exclamation-circle text-info"></i>
            looking for freelancing work. <br>
            web developer, python, flask, react
          </P></li>
          <li>
            <a class="text-decoration-none link-secondary" target="_blank" 
                href="mailto:developer.bhaskarn@gmail.com">
              <i class="bi bi-envelope-fill mr-1"></i><span class="ml-1"> developer.bhaskarn@gmail.com</span></a></li>
        </ul>
      </div>
        <div class="col">
          <h5>Social Links</h5>
          <ul class="list-unstyled ">
            <li><a class="text-decoration-none" target="_blank" href="https://twitter.com/BhaskarNar"><i class="bi bi-twitter pe-2"></i>Twitter</a></li>
            <li><a class="text-decoration-none" target="_blank" href="https://www.instagram.com/bhaskarathome"><i class="bi bi-instagram"></i><span class="ps-2">Instagram</span></a></li>
            <li><a class="text-decoration-none" target="_blank" href="https://www.facebook.com/bhaskar.nar.11"><i class="bi bi-facebook"></i><span class="ps-2">Facebook</span></a></li>
          </ul>
        </div>
      </div>
      <div class="row py-2">
          <span class="text-center"> &copy 2021 Bhaskar Nar, all rights reserved. </span>
      </div>
    </div>
  
  {% endblock %}

src/templates/_header.html
{% block header %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{{url_for("static", filename="mandala128px.png")}}" width="40px" height="40px" alt="brand-logo">
            Bhaskar.in
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about-me">About Me</a>
            </li>
            </ul>
        </div>
        </div>
    </nav>
{%endblock%}

src/templates/admin-dashboard.html
{% extends 'base.html' %}
{%block title%}
    Bhaskar's Blog - Admin Dashboard
{%endblock%}
{% block header%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid mx-2">
        <a class="navbar-brand" href="/">
            <img src="{{url_for("static", filename="mandala128px.png")}}" width="40px" height="40px" alt="brand-logo">
            Bhaskar.in
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class=" collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="/">Home</a>
                </li>
            </ul>
            {% if not user %}
                <div class="nav-item">
                    <a class="nav-link" href="{{url_for("auth.user_login")}}">Log in</a>
                </div>
            {% else %}
                <div class="nav-item dropdown">
                    <a class="btn btn-link dropdown-toggle dropdown-toggle text-decoration-none text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-person-circle me-2"></i>{{ user.name }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">{{ user.email }}</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('.dashboard_page') }}">Dashboard</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('.account_settings') }}">Account Settings</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.user_logout') }}">Logout</a></li>
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
</nav>
{%endblock%}

{%block content%}
    <div class="container my-3">
            {% with alerts = get_flashed_messages(with_categories=True) %}
                {% if alerts %}
                    {% for type, alert in alerts %}
                    <div class="alert alert-{{ type }} d-flex align-items-center alert-dismissible fade show" role="alert">
                        <i style="font-size: 24px;" class="bi {{ "bi-check-circle-fill" if type == 'success' else "bi-exclamation-circle-fill" }} me-2"></i>
                        <div>{{alert}}</div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}    
                {%endif%}
            {% endwith %}<div class="row">
            <div class="col">
                {%if messages %}
                    {% for message in messages: %}
                        <div class="card my-3">
                            <div class="card-body">
                                <h5 class="card-title">Sender Name: {{message.name}} <span class="badge bg-info">New</span></h5>
                                <a class="text-decoration-none" href="mailto:{{message.email}}">
                                    <h6 class="card-subtitle mb-2 text-muted"><i class="bi bi-envelope-open me-2"></i>{{message.email}}</h6>
                                </a>
                                <p class="card-text">{{message.message}}</p>
                                <span>
                                    <form method="POST" action="{{url_for("admin.dashboard_page")}}?delete=1&id={{message.id}}">
                                        <button id="message-delete" class="btn btn-primary">Remove message</button>
                                    </form>
                                </span>
                            </div>
                            <div class="card-footer text-muted">
                                Sent at: {{message.sent_date}}
                              </div>
                        </div>
                    {% endfor %}
                {% else: %}
                    <div class="alert alert-warning fade show mt-3" role="alert">
                        <strong>Holy guacamole!</strong> There is no message to show
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{%endblock%}

src/templates/admin-settings.html
{% extends 'admin-dashboard.html' %}

{% block title %}
    Admin - Settings
{% endblock %}

{% block content %}
    <div class="container my-3">
        <div class="card">
            <div class="card-header"><h3>Admin Settings</h3></div>
            <div class="card-body">
            <form novalidate method="POST" action="">
                    <div class="card-body">
                        <fieldset>
                            {{ form.csrf_token() }}
                            <div class="row">
                                <div class="col-md-3 mb-3">
                                    {{ form.name.label(class = "form-label") }}
                                    {% if form.name.errors %}
                                        {{ form.name(class="form-control is-invalid", placeholder="e.g - Rajesh Kuthrapalli") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.name.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}                    
                                        {{ form.name(class="form-control", placeholder="e.g - Rajesh Kuthrapalli") }}
                                    {% endif %}
                                </div>
                                <div class="col-md-3 mb-3">
                                    {{ form.email.label(class = "form-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control is-invalid", placeholder="e.g - rajesh.k@email.com") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}                    
                                        {{ form.email(class="form-control", placeholder="e.g - rajesh.k@email.com") }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="col-md-6 mb-3">
                                        {{ form.password.label(class = "form-label") }}
                                        {% if form.password.errors %}
                                            {{ form.password(class="form-control is-invalid", placeholder="e.g - rajesh.k@email.com") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}                    
                                            {{ form.password(class="form-control", placeholder="enter your password") }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="col-md-6 mb-3">
                                        {{ form.cnf_password.label(class = "form-label") }}
                                        {% if form.cnf_password.errors %}
                                            {{ form.cnf_password(class="form-control is-invalid", placeholder="Confirm password") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.cnf_password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}                    
                                            {{ form.cnf_password(class="form-control", placeholder="Confirm password") }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-6">
                                {{ form.submit(class="btn btn-primary btn-lg") }}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/style.css") }}">
    <title>
      {% block title %}
        
      {% endblock %}
    </title>
  </head>
  <body>
  <header >
    {% block header %}
      {% include '_header.html' %}
    {%endblock%}
  </header>
    <!-- <div class="container-fluid"> -->
      {% block content %}

      {% endblock %}
    <!-- </div> -->
    <footer class="bd-footer bg-light">
      {% block footer %}
        {% include '_footer.html' %}
      {%endblock%}
   </footer>
    <!-- Optional JavaScript;-->

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="{{url_for("static", filename="js/main.bundle.js")}}"></script>
  </body>
</html>

src/templates/contact.html
{% extends 'base.html' %}
{% block title %}
    Contact - Bhaskar.in
{% endblock %}

{%block content %}
<div class="container my-4">
    {% with alerts = get_flashed_messages(with_categories=True) %}
        {% if alerts %}
            {% for type, alert in alerts %}
            <div class="alert alert-{{ type }} d-flex align-items-center alert-dismissible fade show" role="alert">
                <i style="font-size: 24px;" class="bi {{ "bi-check-circle-fill" if type == 'success' else "bi-exclamation-circle-fill" }} me-2"></i>
                <div>{{alert}}</div>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endfor %}    
        {%endif%}
    {% endwith %}
    <h3>Contact Me</h3>
    <form novalidate method="POST" action="">
        {{ form.csrf_token() }}
        <div class="row">
            <div class="col-md-6 mb-3 ">
                {{ form.name.label(class="form-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control is-invalid", placeholder="e.g - Rajesh Kuthrappali") }}

                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control", placeholder="e.g - Rajesh Kuthrappali") }}              
                {% endif %}
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-6 mb-3 has-validation">
                {{ form.email.label(class = "form-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid", placeholder="e.g - rajesh.k@email.com") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}                    
                    {{ form.email(class="form-control", placeholder="e.g - rajesh.k@email.com") }}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3 ">
                {{ form.message.label(class="form-label") }}
                {% if form.message.errors %}
                    {{ form.message(class="form-control is-invalid", placeholder="Type your message...") }}
                    <div class="invalid-feedback">
                        {% for error in form.message.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.message(class="form-control", placeholder="Type your message...") }}
                {% endif %}
            </div>
        </div>
        {{ form.submit(class="btn btn-lg btn-primary") }}
    </form>
    
    </div>
{% endblock %}

src/templates/error-page.html
{%extends 'base.html'%}
{%block title%}
    Oops! page not found
{%endblock%}

{%block header%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-center">
        <a class="navbar-brand" href="/">
            <img src="{{url_for("static", filename="mandala128px.png")}}" width="40px" height="40px" alt="brand-logo">
            Bhaskar.in
        </a>       
    </div>
</nav>
{%endblock%}

{%block content%}
    <div class="container" >
        <div class="row">
            <div class="col-12 text-center my-5">
                <img style="max-width: 100%; width: fit-content;" src="{{url_for("static", filename="error-page.png")}}" alt="error-page">
                <p>
                    <h2>Page Not found</h2>
                    <h4>The requested URL was not found on the server. If you entered <br> 
                    the URL manually please check your spelling and try again.</h4>
                </p>
                    <a type="button" href="{{url_for("home_page")}}" class="btn btn-primary">Return to Home Page</a>
            </div>
        </div>
        
        
    </div>
{%endblock%}

src/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Bhaskar's - personal blog
{% endblock  %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
{% endblock  %}